"""create design_systems table

Revision ID: b5f7610253dd
Revises: 5ff1c87ccf65
Create Date: 2025-03-15 16:48:33.547481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f7610253dd'
down_revision = '5ff1c87ccf65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
