"""create design_systems table

Revision ID: 16bc091e96dc
Revises: b5f7610253dd
Create Date: 2025-03-15 16:52:39.095220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16bc091e96dc'
down_revision = 'b5f7610253dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
