"""Create tables

Revision ID: 77cc46155398
Revises: 16bc091e96dc
Create Date: 2025-03-15 17:28:05.094424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77cc46155398'
down_revision = '16bc091e96dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('design_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_systems_id'), 'design_systems', ['id'], unique=False)
    op.create_index(op.f('ix_design_systems_name'), 'design_systems', ['name'], unique=True)
    op.create_table('dynamic_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dynamic_data_id'), 'dynamic_data', ['id'], unique=False)
    op.create_index(op.f('ix_dynamic_data_title'), 'dynamic_data', ['title'], unique=False)
    op.create_table('experiences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('achievements', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('projects', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('technologies', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('github', sa.String(), nullable=True),
    sa.Column('appStore', sa.String(), nullable=True),
    sa.Column('playStore', sa.String(), nullable=True),
    sa.Column('achievements', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('data_tags',
    sa.Column('data_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_id'], ['dynamic_data.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('projects')
    op.drop_table('experiences')
    op.drop_index(op.f('ix_dynamic_data_title'), table_name='dynamic_data')
    op.drop_index(op.f('ix_dynamic_data_id'), table_name='dynamic_data')
    op.drop_table('dynamic_data')
    op.drop_index(op.f('ix_design_systems_name'), table_name='design_systems')
    op.drop_index(op.f('ix_design_systems_id'), table_name='design_systems')
    op.drop_table('design_systems')
    # ### end Alembic commands ###
